# Generated by Django 4.2.8 on 2023-12-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='TrendEglence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
            ],
        ),
    ]
