# Generated by Django 4.2.8 on 2023-12-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menuler',
            new_name='MenulerMod',
        ),
        migrations.RenameModel(
            old_name='TrendEglence',
            new_name='TariflerMod',
        ),
        migrations.RenameModel(
            old_name='Tarifler',
            new_name='TrendEglenceMod',
        ),
    ]
