# Generated by Django 4.2.8 on 2023-12-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_rename_menuler_menulermod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulermod',
            old_name='text',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='tariflermod',
            old_name='text',
            new_name='subtitle',
        ),
        migrations.RenameField(
            model_name='trendeglencemod',
            old_name='text',
            new_name='subtitle',
        ),
    ]
