# Generated by Django 4.2.8 on 2023-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_rename_text_menulermod_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulermod',
            name='subtitle',
            field=models.TextField(verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='tariflermod',
            name='subtitle',
            field=models.TextField(verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='trendeglencemod',
            name='subtitle',
            field=models.TextField(verbose_name='Alt başlık'),
        ),
    ]
