# Generated by Django 4.2.8 on 2023-12-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0004_alter_menulermod_subtitle_alter_tariflermod_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulermod',
            name='text',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='tariflermod',
            name='text',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='trendeglencemod',
            name='text',
            field=models.TextField(null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='menulermod',
            name='subtitle',
            field=models.CharField(max_length=50, verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='tariflermod',
            name='subtitle',
            field=models.CharField(max_length=50, verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='trendeglencemod',
            name='subtitle',
            field=models.CharField(max_length=50, verbose_name='Alt başlık'),
        ),
    ]
