# Generated by Django 4.2.8 on 2023-12-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_menulermod_text_tariflermod_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulermod',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='menulermod',
            name='image',
            field=models.ImageField(blank=True, upload_to=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='menulermod',
            name='subtitle',
            field=models.CharField(max_length=450, verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='menulermod',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='tariflermod',
            name='image',
            field=models.ImageField(blank=True, upload_to=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tariflermod',
            name='subtitle',
            field=models.CharField(max_length=450, verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='tariflermod',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='trendeglencemod',
            name='image',
            field=models.ImageField(blank=True, upload_to=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='trendeglencemod',
            name='subtitle',
            field=models.CharField(max_length=450, verbose_name='Alt başlık'),
        ),
        migrations.AlterField(
            model_name='trendeglencemod',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='İçerik'),
        ),
    ]
