# Generated by Django 4.2.8 on 2023-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0006_menulermod_slug_alter_menulermod_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariflermod',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='trendeglencemod',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
