# Generated by Django 4.2.8 on 2023-12-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_tariflermod_slug_trendeglencemod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulermod',
            name='slug_category',
            field=models.SlugField(null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='tariflermod',
            name='slug_category',
            field=models.SlugField(null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='trendeglencemod',
            name='slug_category',
            field=models.SlugField(null=True, verbose_name='Kategori'),
        ),
    ]
