# Generated by Django 4.2.8 on 2023-12-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0008_menulermod_slug_category_tariflermod_slug_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulermod',
            name='slug_category',
        ),
        migrations.RemoveField(
            model_name='tariflermod',
            name='slug_category',
        ),
        migrations.RemoveField(
            model_name='trendeglencemod',
            name='slug_category',
        ),
    ]
