# Generated by Django 4.2.8 on 2023-12-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0009_remove_menulermod_slug_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulermod',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='tariflermod',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='trendeglencemod',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
    ]
