# Generated by Django 4.2.8 on 2024-01-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_alter_menulermod_title_alter_tariflermod_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulermod',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='tariflermod',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='trendeglencemod',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='Kategori'),
        ),
    ]
