# Generated by Django 4.2.8 on 2024-01-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0011_menulermod_category_tariflermod_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulermod',
            name='image',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='tariflermod',
            name='image',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='trendeglencemod',
            name='image',
            field=models.ImageField(blank=True, upload_to=None, verbose_name='Fotoğraf'),
        ),
    ]
