# Generated by Django 4.2.8 on 2024-01-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0012_alter_menulermod_image_alter_tariflermod_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulermod',
            name='read_time',
            field=models.CharField(max_length=50, null=True, verbose_name='Okuma Süresi'),
        ),
        migrations.AddField(
            model_name='tariflermod',
            name='read_time',
            field=models.CharField(max_length=50, null=True, verbose_name='Okuma Süresi'),
        ),
        migrations.AddField(
            model_name='trendeglencemod',
            name='read_time',
            field=models.CharField(max_length=50, null=True, verbose_name='Okuma Süresi'),
        ),
    ]
