# Generated by Django 4.2.8 on 2024-01-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0013_menulermod_read_time_tariflermod_read_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulermod',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='tariflermod',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='trendeglencemod',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Tarih'),
        ),
    ]
