# Generated by Django 4.2.10 on 2024-04-27 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0018_menulermod_date_tariflermod_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SepetimMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Menü Başlık')),
                ('additionalinfo', models.CharField(max_length=150, verbose_name='Menü İçerik')),
                ('price', models.CharField(max_length=50, verbose_name='Fiyat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='AdresMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Adres Başlığı')),
                ('adrestype', models.CharField(max_length=50, verbose_name='Adres Tipi')),
                ('il', models.CharField(max_length=50, verbose_name='İl')),
                ('ilce', models.CharField(max_length=50, verbose_name='İlce')),
                ('mahalle', models.CharField(max_length=50, verbose_name='Mahalle')),
                ('cadde', models.CharField(max_length=50, verbose_name='Cadde')),
                ('sokak', models.CharField(max_length=50, verbose_name='Sokak')),
                ('binano', models.CharField(max_length=50, verbose_name='Bina No')),
                ('daireno', models.CharField(max_length=50, verbose_name='Daire No')),
                ('bina', models.CharField(max_length=50, verbose_name='Bina Adı')),
                ('adrestarif', models.CharField(max_length=50, verbose_name='Adres Tarifi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
