# Generated by Django 4.2.10 on 2024-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0020_ekbilgimod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekbilgimod',
            name='cinsiyet',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='ekbilgimod',
            name='takim',
            field=models.CharField(blank=True, max_length=50, verbose_name='Takım'),
        ),
    ]
