# Generated by Django 4.2.10 on 2024-04-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0023_alter_sepetimmod_additionalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sepetimmod',
            name='additionalinfo',
        ),
    ]
